# Generated by Selenium IDE
import pytest
import time
import json
import pyautogui
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities



driver = webdriver.Chrome()
driver.get("https://www.nytimes.com/")
driver.maximize_window()
time.sleep(4)

screenWidth, screenHeight = pyautogui.size()    # Macbook pro 13" is 1440x900
targetposx = screenWidth/2
targetposy = 200                                # this is a guess
pyautogui.click(targetposx,targetposy)
time.sleep(5)
driver.switch_to_window(driver.window_handles[1])
url = driver.current_url
print(url)
